### ISSUE TITLE
Unable to logging in with Google+ identity provider

### ISSUE THREAD

**Issue by nagendra29** [auth0/Lock.Android#109]
java.lang.NoSuchFieldError: com.auth0.googleplus.R$string.social_error_title
            at com.auth0.googleplus.GooglePlusIdentityProvider.onConnectionFailed(GooglePlusIdentityProvider.java:147)
            at com.google.android.gms.internal.jm.b(Unknown Source)
            at com.google.android.gms.common.api.c.gJ(Unknown Source)
            at com.google.android.gms.common.api.c.d(Unknown Source)
            at com.google.android.gms.common.api.c$4.onConnectionFailed(Unknown Source)
            at com.google.android.gms.internal.jm.b(Unknown Source)
            at com.google.android.gms.internal.jl$h.b(Unknown Source)
            at com.google.android.gms.internal.jl$h.g(Unknown Source)
            at com.google.android.gms.internal.jl$b.hy(Unknown Source)
            at com.google.android.gms.internal.jl$a.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4517)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by hzalaz** [comment]
@nagendra29 please check you are using the latest version of Lock (1.9.5) and of the G+ integration (2.0.0)
