### ISSUE TITLE
error multiDexEnabled = true api 16

### ISSUE THREAD

**Issue by mauriciocoelho** [auth0/Lock.Android#112]
hello, I was using the 1.7.0 version and functioning normally for api 16, when I had to turn on multiDexEnabled to true and at the same time upgraded to the latest version of auth0. however not opened the activity of Lock for api 16.

I went back to 1.7.0 version and also did not work, then I suppose that is not working with multiDexEnabled = true.

previously already I had some problems with it.

``` java
08-11 17:39:57.326    1649-1649/com.squidit.squid E/GAV4﹕ Thread[main,5,main]: Error dispatching all events on exit, giving up: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1117)
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:908)
            at org.apache.http.impl.SocketHttpClientConnection.shutdown(SocketHttpClientConnection.java:183)
            at org.apache.http.impl.conn.DefaultClientConnection.shutdown(DefaultClientConnection.java:150)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.shutdown(AbstractPooledConnAdapter.java:169)
            at org.apache.http.impl.conn.AbstractClientConnAdapter.abortConnection(AbstractClientConnAdapter.java:378)
            at org.apache.http.impl.client.DefaultRequestDirector.abortConnection(DefaultRequestDirector.java:1031)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:530)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
            at com.google.android.gms.analytics.h.a(Unknown Source)
            at com.google.android.gms.analytics.h.a(Unknown Source)
            at com.google.android.gms.analytics.ag.dispatch(Unknown Source)
            at com.google.android.gms.analytics.w.eD(Unknown Source)
            at com.google.android.gms.analytics.w.dispatch(Unknown Source)
            at com.google.android.gms.analytics.x$b.run(Unknown Source)
            at com.google.android.gms.analytics.x.dY(Unknown Source)
            at com.google.android.gms.analytics.GoogleAnalytics.dY(Unknown Source)
            at com.google.android.gms.analytics.ExceptionReporter.uncaughtException(Unknown Source)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
            at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
            at dalvik.system.NativeStart.main(Native Method)
08-11 17:39:57.326    1649-1649/com.squidit.squid E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.auth0.lock.R$string
            at com.auth0.lock.fragment.LoadingFragment.onCreateView(LoadingFragment.java:37)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at com.auth0.lock.LockActivity.onStart(LockActivity.java:110)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
            at android.app.Activity.performStart(Activity.java:5114)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by hzalaz** [comment]
Never had the need to enable multidex support for one of my Apps but, as far as I can remember, you need to manually load the "extra" dex files generated by multidex in API level lesser than 21, otherwise some classes won't be found by the classloader and hence the exception.

**Comment by mauriciocoelho** [comment]
sorry @hzalaz , I had not set up correctly the multidex
