### ISSUE TITLE
Failed to read info from AndroidManifest.xml

### ISSUE THREAD

**Issue by ritdaw** [auth0/Lock.Android#123]
Through our crashlytics console we are occasionally getting the below error logged, it seems to be only on a few devices out of 100's. Having looked at the source it seems to be an issue reading CONFIGURATION_URL_KEY (com.auth0.lock.configuration-url). We do not have this value in our manifest as the documentation states its optional if ClientID/tenant is specified. Currently using v1.10.1, any ideas?

java.lang.RuntimeException: Unable to create application com.test.app: java.lang.IllegalArgumentException: Failed to read info from AndroidManifest.xml
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
       at android.app.ActivityThread.access$1300(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalArgumentException: Failed to read info from AndroidManifest.xml
       at com.auth0.lock.Lock$Builder.loadFromApplication(Lock.java:620)
       at com.test.app.AppActivity.onCreate(AppActivity.java:91)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
       at android.app.ActivityThread.access$1300(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hzalaz** [comment]
@ritdaw that exception will be only raised if another one (PackageManager.NameNotFoundException) is raised by this line

```java
ApplicationInfo ai = application.getPackageManager().getApplicationInfo(application.getPackageName(), PackageManager.GET_META_DATA);
```

Which means that the application cannot be found with the package name it gets from the application object, which should not happen at all or it should break for all your users. 

If the configurationUrl is not in the manifest will not fail, just ignore it and use the default based on your domainUrl.

How are you building Lock and from where?, by any chance are you overriding the `getPackageName()`?

**Comment by ritdaw** [comment]
@hzalaz Building lock from in the onCreate() method of an extended Application class.  No not overriding getPackageName(). I've never seen the error myself during any testing, just seems to have cropped up a few times in crashlytics.

**Comment by hzalaz** [comment]
@ritdaw that's odd, is that the full trace? (if you can share me the crash report from crashlytics the better, hernan (at) auth0 (dot) com)

**Comment by ritdaw** [comment]
Have sent this to you.

**Comment by hzalaz** [comment]
Oh yes, I'll try to track it in my inbox. In the meantime to avoid reading the values from the `AndroidManifest.xml` and avoiding that rare crash, you can build Lock like this:

```java
        lock = new Lock.Builder()
                .clientId("YOUR_CLIENT_ID")
                .domainUrl("YOUR_DOMAIN")
//Other options
                .build();
``` 
I'll close this for now if you find more info or you get a lot more crashes please reopen it.

**Comment by ritdaw** [comment]
Thanks @hzalaz
