### ISSUE TITLE
Error logging in from google+

### ISSUE THREAD

**Issue by UrbanChrisy** [auth0/Lock.Android#151]
![screenshot_2015-12-10-14-40-45](https://cloud.githubusercontent.com/assets/11880289/11704362/1bd0474a-9f4c-11e5-9c38-932171b69973.png)

annnnnnndddddd logcat info:

```
< Failed to authenticate user
 com.auth0.api.APIClientException: Failed request to https://rezy.au.auth0.com/dbconnections/signup
     at com.auth0.api.internal.SimpleRequest.onResponse(SimpleRequest.java:81)
     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
12-10 14:39:13.938 21379-21379/tk.delacour.rezy E/com.auth0.googleplus.GooglePlusIdentityProvider: Failed to clear G+ Session
                     java.lang.IllegalStateException: GoogleApiClient must be connected.
                         at com.google.android.gms.common.internal.zzv.zza(Unknown Source)
                         at com.google.android.gms.plus.Plus.zzf(Unknown Source)
                         at com.google.android.gms.internal.zzll.clearDefaultAccount(Unknown Source)
                         at com.auth0.googleplus.GooglePlusIdentityProvider.clearSession(GooglePlusIdentityProvider.java:121)
                         at com.auth0.lock.LockActivity.onAuthenticationError(LockActivity.java:224)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at java.lang.reflect.Method.invoke(Method.java:372)
                         at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                         at com.squareup.otto.Bus.dispatch(Bus.java:384)
                         at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
                         at com.squareup.otto.Bus.post(Bus.java:336)
                         at com.auth0.lock.fragment.SignUpFormFragment$SignUpAuthenticationCallback.onFailure(SignUpFormFragment.java:218)
                         at com.auth0.api.authentication.SignUpRequest$1.onFailure(SignUpRequest.java:102)
                         at com.auth0.api.internal.BaseRequest$2.run(BaseRequest.java:95)
                         at android.os.Handler.handleCallback(Handler.java:810)
                         at android.os.Handler.dispatchMessage(Handler.java:99)
                         at android.os.Looper.loop(Looper.java:209)
                         at android.app.ActivityThread.main(ActivityThread.java:5979)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at java.lang.reflect.Method.invoke(Method.java:372)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1044)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:839)>
```

**Comment by hzalaz** [comment]
@UrbanChrisy did you configure your Google's clientId in the dashboard `https://manage.auth0.com/#/connections/social`?

If everything looks ok, can you please send a sample app that can reproduce the issue to support@auth0.com and we'll take a look.

**Comment by UrbanChrisy** [comment]
@hzalaz Yea thats all configured correctly as it works with the in browser Try button.

And heres a link to sample app. https://github.com/UrbanChrisy/Sample

**Comment by hzalaz** [comment]
@UrbanChrisy you'll need to configure your Google OAuth 2 client in the Allowed Client sections, and that client needs to be for an Android app not a web app. This is explained in https://github.com/auth0/Lock-GooglePlus.Android#before-you-start-using-lock-google.

If you need more assistance please send an email to support@auth0.com or join our support channel chat.auth0.com.
