### ISSUE TITLE
IllegalStateException in GoogleIdentityProvider.onPermissionsRequireExplanation

### ISSUE THREAD

**Issue by pmq** [auth0/Lock.Android#331]
Hi,

We upgraded to 1.17.0 and are having a major problem with the native Google authentication. We thought we were using the textbook integration :

```
// setup Auth0 and the native Google integration
ParameterBuilder paramsBuilder = ParameterBuilder.newBuilder();
String scope = ParameterBuilder.SCOPE_OFFLINE_ACCESS + " email";
Map<String, Object> parameters = paramsBuilder.setScope(scope).asDictionary();

LockContext.configureLock(
        new Lock.Builder()
                .loadFromApplication(this)
                .withIdentityProvider(Strategies.GooglePlus, new GoogleIdentityProvider(this))
                .authenticationParameters(parameters)
);
```

When a user uses the Google authentication button, the native integration correctly asks for permission to access the contacts, then if the user cancels that request, all future use of the Google auth button will crash the app with this stacktrace :

```
08-18 22:55:40.078 24786-24786/<REDACTED> E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: <REDACTED>, PID: 24786
                                                              java.lang.RuntimeException: Could not dispatch event: class com.auth0.lock.event.IdentityProviderAuthenticationRequestEvent to handler [EventHandler public void com.auth0.lock.LockActivity.onIdentityProviderAuthentication(com.auth0.lock.event.IdentityProviderAuthenticationRequestEvent)]: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                  at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
                                                                  at com.squareup.otto.Bus.dispatch(Bus.java:386)
                                                                  at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
                                                                  at com.squareup.otto.Bus.post(Bus.java:336)
                                                                  at com.auth0.lock.fragment.SmallSocialListFragment$1.onItemClick(SmallSocialListFragment.java:84)
                                                                  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                  at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                                  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                                  at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                               Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:343)
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                  at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:80)
                                                                  at android.support.v7.app.AlertController.installContent(AlertController.java:214)
                                                                  at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:257)
                                                                  at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                  at android.app.Dialog.show(Dialog.java:295)
                                                                  at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:953)
                                                                  at com.auth0.google.GoogleIdentityProvider.onPermissionsRequireExplanation(GoogleIdentityProvider.java:97)
                                                                  at com.auth0.identity.AuthorizedIdentityProvider.checkPermissions(AuthorizedIdentityProvider.java:156)
                                                                  at com.auth0.identity.AuthorizedIdentityProvider.start(AuthorizedIdentityProvider.java:72)
                                                                  at com.auth0.lock.LockActivity.onIdentityProviderAuthentication(LockActivity.java:296)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                  at com.squareup.otto.Bus.dispatch(Bus.java:384)
                                                                  at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367) 
                                                                  at com.squareup.otto.Bus.post(Bus.java:336) 
                                                                  at com.auth0.lock.fragment.SmallSocialListFragment$1.onItemClick(SmallSocialListFragment.java:84) 
                                                                  at android.widget.AdapterView.performItemClick(AdapterView.java:310) 
                                                                  at android.widget.AbsListView.performItemClick(AbsListView.java:1145) 
                                                                  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066) 
                                                                  at android.widget.AbsListView$3.run(AbsListView.java:3903) 
                                                                  at android.os.Handler.handleCallback(Handler.java:739) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

This is on a Nexus 5, Android 6.0.1, in an app with these settings :

```
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
...
```

Gradle : `2.14.1`
Android Plugin : `com.android.tools.build:gradle:2.1.3`

Debugging a little bit this issue, as the AppCompat dialog builder is using the context from the application, it's true that there is no theme. But the issue should not be there, as we got the code from the Auth0 sample code which also uses the application instance to build the `GoogleIdentityProvider`.

Happy to provide more info if needed. Thanks.

**Comment by pmq** [comment]
I've checked again the sample app in the repo, and I noticed you're using two options that differ from us :
- `.useWebView(true)`
- `.withIdentityProvider(Strategies.GooglePlus, new GooglePlusIdentityProvider(this))` with the deprecated Google provider

Is there a reason for those two surprising options?
Many thanks.

**Comment by hzalaz** [comment]
No reason, the sample in the repo is outdated since we are working on releasing v2 of Lock Android.

For what I see the cause is `You need to use a Theme.AppCompat theme (or descendant) with this activity.` What theme are you setting for LockActivity in your Manifest?

**Comment by pmq** [comment]
Hi Hernan !

We're setting this theme :

```
<activity
        android:name="com.auth0.lock.LockActivity"
        android:theme="@style/Theme.Scanny.Lock"
        android:screenOrientation="portrait"
        android:launchMode="singleTask">
...
```

With this definition :

```
<style name="Theme.Scanny.Lock" parent="Lock.Theme">
    <item name="Auth0.Title.Icon">@style/Theme.Scanny.Lock.Title.Icon</item>
</style>

<style name="Theme.Scanny.Lock.Title.Icon" parent="Lock.Theme.Title.Icon">
    <item name="android:src">@drawable/product_logo</item>
    <item name="android:background">@android:color/white</item>
</style>
```

So it should be a descendent.

**Comment by pmq** [comment]
@hzalaz any news? On my end I can repro very easily with the Lock.Android sample app. I just commented out the `useWebView` call and used the non-deprecated Google provider :

```
    @Override
    public void onCreate() {
        super.onCreate();

        LockContext.configureLock(
                new Lock.Builder()
                        .loadFromApplication(this)
                        .closable(true)
                        .useEmail(true)
                        .usePKCE(true)
                        .fullscreen(false)
                        // .useWebView(true)
                        .withIdentityProvider(Strategies.Facebook, new FacebookIdentityProvider(this))
                        .withIdentityProvider(Strategies.GooglePlus, new GoogleIdentityProvider(this))
        );
    }
```

And the sample app crashes with this exception :

```
08-26 22:20:31.480 7561-7561/com.auth0.app.Lock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.auth0.app.Lock, PID: 7561
                                                                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=211, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.auth0.app.Lock/com.auth0.lock.LockActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:253)
                                                                      at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:76)
                                                                      at android.support.v7.app.AlertController.installContent(AlertController.java:213)
                                                                      at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:240)
                                                                      at android.app.Dialog.dispatchOnCreate(Dialog.java:394)
                                                                      at android.app.Dialog.show(Dialog.java:295)
                                                                      at android.support.v7.app.AlertDialog$Builder.show(AlertDialog.java:902)
                                                                      at com.auth0.google.GoogleIdentityProvider.onPermissionsRequireExplanation(GoogleIdentityProvider.java:97)
                                                                      at com.auth0.identity.AuthorizedIdentityProvider.onRequestPermissionsResult(AuthorizedIdentityProvider.java:143)
                                                                      at com.auth0.lock.LockActivity.onRequestPermissionsResult(LockActivity.java:175)
                                                                      at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
                                                                      at android.app.Activity.dispatchActivityResult(Activity.java:6460)
                                                                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                                                                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                                                                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
08-26 22:20:31.486 789-3056/? W/ActivityManager:   Force finishing activity com.auth0.app.Lock/com.auth0.lock.LockActivity
```

This is a release blocker for us and probably for everyone using Lock.Android with target >= 23, any ETA on fixing this in a 1.17.1 release ?

**Comment by hzalaz** [comment]
No ETA since we are working on finishing version 2 of the library. What sample app you mean, the one in the repo?

**Comment by pmq** [comment]
Yes, app/ in the repo. What should we do then ? Because to be honest, we have little choice. We cannot go back to our previous version of Lock as we are now targeting v23. So if I'm not mistaken, there are two options :
- Use Lock.Android 2 in beta and check if it covers our basic need ;
- Patch Lock.Android 1.17.0 ourselves.

What's your take on this ? Thanks.

**Comment by hzalaz** [comment]
I'd suggest to try the sample app from https://docs.auth0.com since it's been a while since we work in  v1 (besides bug fixing) and I can't recall in what state we left it.

**Comment by hzalaz** [comment]
Also I believe is a config issue more than a Lock bug, unless we rework how to show that alert.

**Comment by pmq** [comment]
OK so to make sure I understand; I've checkout the new Auth0 project with the samples. I believe you're advising for solution 1: `Use Lock.Android 2 in beta and check if it covers our basic need`.

From the last 30 minutes playing with 2.0.0-beta.3, a simple permission problem with Android 23 is going to turn into a full scale nightmare, as it breaks all of our token refresh code and JWT expiration checks, which obviously are sensitive pieces of code.

**Comment by hzalaz** [comment]
I didn't recommend using v2 since it's a breaking change in API but to use the sample for v1 from the quickstart. However I forgot we already migrated them to v2, so I'd have to debug this sometime next week. 
I'd recommend, if you need to support Api 23 right now, to drop native integration till I have time to check that out and see what's wrong. It's a Theme that does not extend from AppCompat or a wrong inheritance somewhere in Lock

**Comment by pmq** [comment]
Makes sense, thank you Hernan. We dropped the native integration as we needed to release fast. Let me know if you find a real solution.

**Comment by hzalaz** [comment]
@pmq just reproduced this and it's an issue in our end where some scenarios were not properly considered. Will try to make a fix this week and release.

**Comment by hzalaz** [comment]
Will try to contain this to the Google integration but maybe some Lock changes are necessary so I'll keep this open here.

**Comment by pmq** [comment]
@hzalaz thanks Hernan !

**Comment by hzalaz** [comment]
@pmq will be officially fixed when that last pr ☝️ is merged and released
