### ISSUE TITLE
Getting NPE        at com.auth0.android.lock.views.ClassicLockView.showProgress(ClassicLockView.java:290)

### ISSUE THREAD

**Issue by nagendra29** [auth0/Lock.Android#395]
java.lang.RuntimeException: Unable to resume activity 
com.auth0.android.lock.LockActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2795)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2824)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
       at android.app.ActivityThread.access$800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5105)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.auth0.android.lock.views.ClassicLockView.showProgress(ClassicLockView.java:290)
       at com.auth0.android.lock.LockActivity.onNewIntent(LockActivity.java:280)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1161)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2319)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2824)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
       at android.app.ActivityThread.access$800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5105)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by hzalaz** [comment]
@nagendra29 any repro steps? How did you trigger it? Please add all the information you can otherwise we won't be able to see what's wrong
