### ISSUE TITLE
Gson error on opening lock with new client_id

### ISSUE THREAD

**Issue by TheUberCatman** [auth0/Lock.Android#417]
I decided i want to use a second client_id for development, but as soon as i switched the client_id, the lock give this error: `com.google.gson.JsonParseException: Missing required attribute callback`. but it still works with my other client_id. This 'response' is very unclear.

I'm using the latest lock version for android.

**Comment by TheUberCatman** [comment]
05-23 15:20:44.144 2002-2149/com.schedular.bertuswisman.schedular E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                                    Process: com.schedular.bertuswisman.schedular, PID: 2002
                                                                                    Theme: themes:{}
                                                                                    com.google.gson.JsonParseException: Missing required attribute callback
                                                                                        at com.auth0.android.lock.internal.configuration.GsonDeserializer.requiredValue(GsonDeserializer.java:40)
                                                                                        at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:51)
                                                                                        at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:40)
                                                                                        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                                                                                        at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                                        at com.google.gson.Gson.fromJson(Gson.java:852)
                                                                                        at com.google.gson.Gson.fromJson(Gson.java:801)
                                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher.parseJSONP(ApplicationFetcher.java:132)
                                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher.access$100(ApplicationFetcher.java:51)
                                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher$1.onResponse(ApplicationFetcher.java:99)
                                                                                        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                                        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                        at java.lang.Thread.run(Thread.java:818)
```

**Comment by lbalmaceda** [comment]
@TheUberCatman I agree the message is not the best, it's a generic one explaining a missing required attribute. In this case your client is missing a callback url in the "allowed callback urls" textfield. This is a dashboard configuration issue avoidable if you've followed the [quickstarts](https://auth0.com/docs/quickstart/native/android).
