### ISSUE TITLE
 Missing required attribute callback

### ISSUE THREAD

**Issue by KingIdee** [auth0/Lock.Android#439]
I get this error (com.google.gson.JsonParseException: Missing required attribute callback) whenever I call the LockActivity on my app. I am using 'com.auth0.android:lock:2.7.0' 
The full log is here

com.google.gson.JsonParseException: Missing required attribute callback
                                                                        at com.auth0.android.lock.internal.configuration.GsonDeserializer.requiredValue(GsonDeserializer.java:40)
                                                                        at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:51)
                                                                        at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:40)
                                                                        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
                                                                        at com.google.gson.Gson.fromJson(Gson.java:887)
                                                                        at com.google.gson.Gson.fromJson(Gson.java:852)
                                                                        at com.google.gson.Gson.fromJson(Gson.java:801)
                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher.parseJSONP(ApplicationFetcher.java:132)
                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher.access$100(ApplicationFetcher.java:51)
                                                                        at com.auth0.android.lock.internal.configuration.ApplicationFetcher$1.onResponse(ApplicationFetcher.java:99)
                                                                        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
09-21 09:26:10.508 4479-4521/com.idee.auth0kotlin E/Surface: getSlotFromBufferLocked: unknown buffer: 0xae431150

**Comment by lbalmaceda** [comment]
You're not following the steps correctly 🙂 . If you're just using the readme check [this link](https://github.com/auth0/Lock.Android#usage). If that's not the case, please tell us which guide you're following so we can fix it.

**Comment by KingIdee** [comment]
Ouch! Thanks for the quick response. One more thing just the Facebook button is showing. How can I get Google button to show and the normal username-password input.

**Comment by lbalmaceda** [comment]
Lock will use whatever you've configured in your [Auth0 application](https://manage.auth0.com/#/clients). The first step would be to [add the connections globally](https://manage.auth0.com/#/connections) and then enable them for each Auth0 Client that you want it to be shown. There's an option on Lock sdks to filter them locally. If you're not using that option and you have them enabled in the dashboard, you should be seeing them.

**Comment by KingIdee** [comment]
Yeaa.. Just realized and fixed it. I also added Lock.newBuilder(auth0, callback)
                .allowSignUp(true)
                .allowLogIn(true)
                .allowForgotPassword(true). build();

For standard signUp and logIn.
