### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method createClient(ZZ)Lcom/squareup/okhttp/OkHttpClient; in class Lcom/auth0/android/request/internal/OkHttpClientFactory; or its super classes (declaration of 'com.auth0.android.request.internal.OkHttpClientFactory'

### ISSUE THREAD

**Issue by francoj11** [auth0/Lock.Android#518]
Lock crashes with the new Auth0 1.15.0 version.
It seems its trying to call a method from OkHttpClientFactory called 'createClient' that have changed its signature.

`at com.auth0.android.lock.LockActivity.onFetchApplicationRequest(LockActivity.java:304)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
        at com.squareup.otto.Bus.dispatch(Bus.java:385)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
        at com.squareup.otto.Bus.post(Bus.java:337)
        at com.auth0.android.lock.LockActivity.onCreate(LockActivity.java:149)
        at android.app.Activity.performCreate(Activity.java:6151)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2597)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
        at android.app.ActivityThread.access$1200(ActivityThread.java:188)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5940)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)`

**Comment by lbalmaceda** [comment]
That is expected as the class changed when they introduced the individual timeouts override support. Also, this library at the current version `2.11.1` is using Auth0.Android version `1.14.1`. Unless you force a dependency version this shouldn't be a problem at all. 
I'll make a new release soon using the latest SDK version.
