### ISSUE TITLE
Auth0 Custom Domain Login Issue

### ISSUE THREAD

**Issue by ureshpatel** [auth0/Lock.Android#547]
Hello,

We are not able to use this SDK with custom domain and documentation is not clear about what we need to pass values.
We are using below code for Auth0 to launch Lock Activity for facebook and google connections.

 private fun getAccount(): Auth0 {
        val account = Auth0("CLIENT ID HERE","XXX.YYY.artofliving.ZZZ","empty-pond-5657-cd-XXXXXXXX.edge.tenants.auth0.com")

        account.isOIDCConformant = true
        account.isLoggingEnabled = true

        return account
    }

It gives error after we added custom domain only.

API URL which is fired while launching app,
-> GET https://empty-pond-5657-cd-2s2wkgg9zuu037hy.edge.tenants.auth0.com/client/Qt9XqbrfF5wvA50g2HGxHv3224RmorBk.js

Error and StackTrace of exception is as below,

> E/ApplicationFetcher: Failed to fetch the Application: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
        at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:204)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.access$100(Call.java:35)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192) 
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149) 
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) 
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) 
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) 
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) 
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) 
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) 
        at com.squareup.okhttp.Call.getResponse(Call.java:286) 
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) 
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:204) 
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232) 
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) 
        at com.squareup.okhttp.Call.access$100(Call.java:35) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495) 
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418) 
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339) 
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94) 
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208) 
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375) 
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224) 
        at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192) 
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149) 
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112) 
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184) 
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) 
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) 
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) 
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) 
        at com.squareup.okhttp.Call.getResponse(Call.java:286) 
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) 
        at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:204) 
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232) 
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) 
        at com.squareup.okhttp.Call.access$100(Call.java:35) 
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-08-20 21:41:31.346 26051-26155/com.aol.app E/LockActivity: Failed to fetch the application: Failed to fetch the Application
    com.auth0.android.authentication.AuthenticationException: Failed to fetch the Application
        at com.auth0.android.lock.internal.configuration.ApplicationFetcher$1.onFailure(ApplicationFetcher.java:92)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.auth0.android.Auth0Exception: Failed to fetch the Application: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.auth0.android.lock.internal.configuration.ApplicationFetcher$1.onFailure(ApplicationFetcher.java:91)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:185) 
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

![Screenshot_1566317632](https://user-images.githubusercontent.com/5997718/63364945-2e3f7e80-c394-11e9-848a-7f1ffc68b2a7.png)

**Comment by MAX-POLKOVNIK** [comment]
I have tried to move to custom domain today. Result as same on screenshot.

In custom domain documentation page you can see note below:
![image_2019_09_13T15_03_11_392Z](https://user-images.githubusercontent.com/8066100/64881231-6b8de800-d684-11e9-99db-764ce6a45728.png)

So I guess android auth0 lock doesn't support custom domain

**Comment by lbalmaceda** [comment]
@ureshpatel It seems the configuration domain you passed has an invalid cert and HTTPS validation doesn't pass. If I try to open that URL in the browser I get the following error:

![image](https://user-images.githubusercontent.com/3900123/64979425-1291a000-d88e-11e9-91cc-b24651f5854c.png)

**Comment by lbalmaceda** [comment]
Closing due to inactivity.. If this was not resolved please re-open.
