### ISSUE TITLE
Social Login does not work

### ISSUE THREAD

**Issue by hoang-ei** [auth0/Lock.Android#594]
Seems like all social logins (Google and Apple) on Android does not work suddenly, we didn't change anything on auth0 tenant. 
Our Web works, embedded Lock on iOS works too, only Android has issues. 

`E/LockActivity: Failed to authenticate the user: THERE WAS AN ERROR PROCESSING THE SIGN IN
    com.auth0.android.authentication.AuthenticationException: Could not verify the ID token
        at com.auth0.android.provider.OAuthManager$2$1.onFailure(OAuthManager.java:202)
        at com.auth0.android.provider.OAuthManager$2$1.onFailure(OAuthManager.java:193)
        at com.auth0.android.provider.OAuthManager$3.onFailure(OAuthManager.java:228)
        at com.auth0.android.provider.OAuthManager$3.onFailure(OAuthManager.java:224)
        at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:66)
        at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:59)
        at com.auth0.android.request.internal.BaseRequest.postOnSuccess(BaseRequest.java:93)
        at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:77)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.auth0.android.provider.TokenValidationException: Could not find a public key for kid "null"`

**Comment by lbalmaceda** [comment]
By any chance, are you using rules and changing the ID token contents?

**Comment by hoang-ei** [comment]
I am not sure what rules you mean, but as far as I know we don't change ID token contents

**Comment by lbalmaceda** [comment]
I meant [Auth0 Rules](https://auth0.com/docs/rules) as those could be changing the claim values, but they are set up on the dashboard so if you never touched that, it should be fine. 

According to the last line in that stack-trace, it says the key-id value ("kid" claim on the ID token) was null and that should never be the case. Can you share an ID token here for reference? otherwise, I'd need a [sample](https://stackoverflow.com/help/minimal-reproducible-example) for us to reproduce. You can push that to Github and if this is an SDK issue we can help you.

**Comment by hoang-ei** [comment]
I tried to debug for AuthenticationCallback and it doesn't even go inside onAuthentication(Credentials credentials) method so I cannot provide you ID token.

**Comment by hoang-ei** [comment]
Sorry for inconvenience seems our Android had issue with OICD settings.
