### ISSUE TITLE
NoSuchMethodError Auth0Exception

### ISSUE THREAD

**Issue by StuStirling** [auth0/Lock.Android#664]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/Lock.Android#readme) and [Examples](https://github.com/auth0/Lock.Android/blob/main/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0.android/lock/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Lock.Android/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My project is using Java 17. Whenever I attempt to launch the `PasswordlessLock`. This worked fine prior to updating auth0 to latest or upgrading to 17.

I cannot downgrade as I'm compiling against android sdk `34`.

Here is the stack trace.

```
Caused by java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lcom/auth0/android/Auth0Exception;)V in class Lcom/auth0/android/authentication/AuthenticationException; or its super classes (declaration of 'com.auth0.android.authentication.AuthenticationException' appears in base.apk)
       at com.auth0.android.lock.internal.configuration.ApplicationFetcher$FetchTask.makeApplicationRequest(ApplicationFetcher.java:116)
       at com.auth0.android.lock.internal.configuration.ApplicationFetcher$FetchTask.doInBackground(ApplicationFetcher.java:102)
       at com.auth0.android.lock.internal.configuration.ApplicationFetcher$FetchTask.doInBackground(ApplicationFetcher.java:91)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

### Reproduction

1. Compile a release build with minifyEnabled as true.
2. Attempt to launch the `PasswordlessLock` 
3. Crash

### Additional context

Kotlin - 1.9.20

### Lock.Android version

3.2.2

### Android version(s)

11

**Comment by kevincmojo** [comment]
I'm also seeing this issue using java 18. Is Lock.Android still supported?

**Comment by tristan-littlepay** [comment]
Same problem here. It's persistent when putting the phone into Airplane mode.

**Comment by pretRossB** [comment]
Integrated the library to test using the instructions on https://auth0.com/docs/libraries/lock-android and get this error. I guess the library has been abandoned as lat update was in 2023?
