### ISSUE TITLE
Google+ signup fails after revoking app's rights. 

### ISSUE THREAD

**Issue by xorgate** [auth0/Lock.Android#78]
I have an app that uses Google+ signup. This works, it asks which account i want to use, I select the one present, I get the google dialog asking for permission, i hit ok. All fine.

Then I close my app, and in the Google+ app I revoke the rights of my app.

I would expect the same procedure as before to be run, asking me for permission.
Instead, I get the following screen:
![device-2015-05-21-152941](https://cloud.githubusercontent.com/assets/1864630/7749503/596321fe-ffce-11e4-9469-4ca71d9244a9.png)

Logcat:

05-21 15:17:15.369  12225-12225/<redacted>E/com.auth0.googleplus.GooglePlusIdentityProvider﹕ Connection failed with unrecoverable error
05-21 15:17:15.369  12225-12225/<redacted> E/com.auth0.lock.LockActivity﹕ Failed to authenticate user
05-21 15:17:15.369  12225-12225/<redacted> E/com.auth0.googleplus.GooglePlusIdentityProvider﹕ Failed to clear G+ Session
    java.lang.IllegalStateException: GoogleApiClient must be connected.
            at com.google.android.gms.common.internal.zzv.zza(Unknown Source)
            at com.google.android.gms.plus.Plus.zzf(Unknown Source)
            at com.google.android.gms.internal.zzll.clearDefaultAccount(Unknown Source)
            at com.auth0.googleplus.GooglePlusIdentityProvider.clearSession(GooglePlusIdentityProvider.java:108)
            at com.auth0.lock.LockActivity.onAuthenticationError(LockActivity.java:221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:384)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
            at com.squareup.otto.Bus.post(Bus.java:336)
            at com.auth0.lock.identity.LockIdentityProviderCallback.onFailure(LockIdentityProviderCallback.java:62)
            at com.auth0.googleplus.GooglePlusIdentityProvider.onConnectionFailed(GooglePlusIdentityProvider.java:147)
            at com.google.android.gms.common.internal.zzj.zzj(Unknown Source)
            at com.google.android.gms.common.api.zze.zzf(Unknown Source)
            at com.google.android.gms.common.api.zze.zzc(Unknown Source)
            at com.google.android.gms.common.api.zze.zzc(Unknown Source)
            at com.google.android.gms.common.api.zze$zza$1.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

using:
    compileSdkVersion 21
    buildToolsVersion "22.0.1"
    compile 'com.auth0.android:lock:1.7.0'
    compile 'com.auth0.android:lock-googleplus:1.7.0'
    compile 'com.google.android.gms:play-services-plus:7.3.0'

**Comment by hzalaz** [comment]
@xorgate seems to be that the new `play-services` changed the way this error should be handled. I'll update the G+ integration to use 7.+ version and check this (now it's using 6.+).

**Comment by hzalaz** [comment]
Fixed in Lock-GooglePlus.Android repo
